export interface Question {
  id: string;
  situation: string;
  emoji: string;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
  tips: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  ageGroup: '6-8' | '9-10' | '11-12';
}

export interface Topic {
  id: string;
  title: string;
  description: string;
  icon: string;
  difficulty: number;
  questions: Question[];
}

export const questionsData: Topic[] = [
  {
    id: 'communication',
    title: 'Giao Tiếp',
    description: 'Học cách nói chuyện và lắng nghe',
    icon: '💬',
    difficulty: 3,
    questions: [
      {
        id: 'comm_1',
        situation: 'Bạn muốn mượn đồ chơi của bạn nhưng bạn ấy đang chơi',
        emoji: '🤔',
        question: 'Bạn sẽ làm gì?',
        options: [
          'Chờ đợi và hỏi lịch sự khi bạn ấy chơi xong',
          'Lấy luôn đồ chơi mà không hỏi',
          'La hét để bạn ấy đưa cho mình',
          'Bỏ đi và không nói gì',
        ],
        correct: 0,
        explanation:
          'Chờ đợi và hỏi lịch sự thể hiện sự tôn trọng và kỹ năng giao tiếp tốt.',
        tips: "Luôn nhớ nói 'xin chào', 'cảm ơn' và 'xin lỗi' khi cần thiết!",
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'comm_2',
        situation: 'Bạn không hiểu bài tập mà cô giáo vừa giải thích',
        emoji: '😕',
        question: 'Bạn nên làm gì?',
        options: [
          'Giơ tay và lịch sự hỏi cô giáo',
          'Ngồi im và làm bừa',
          'Hỏi bạn bên cạnh một cách thầm lặng',
          'Chờ đến cuối giờ rồi hỏi',
        ],
        correct: 0,
        explanation:
          'Hỏi ngay khi chưa hiểu giúp bạn học tốt hơn và thể hiện sự chủ động.',
        tips: 'Đừng ngại hỏi khi chưa hiểu - đó là cách tốt nhất để học!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'comm_3',
        situation: 'Bạn muốn tham gia nhóm chơi của các bạn khác',
        emoji: '😊',
        question: 'Cách tốt nhất để xin tham gia là gì?',
        options: [
          "Đến gần và hỏi: 'Mình có thể chơi cùng được không?'",
          'Đứng xa và chờ các bạn mời',
          'Chen vào giữa mà không hỏi',
          "La to: 'Tôi cũng muốn chơi!'",
        ],
        correct: 0,
        explanation:
          'Hỏi lịch sự thể hiện sự tôn trọng và tăng cơ hội được chấp nhận.',
        tips: 'Nụ cười và lời nói nhẹ nhàng sẽ giúp bạn dễ được chấp nhận hơn!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'comm_4',
        situation: 'Bạn bè nói chuyện với bạn nhưng bạn đang bận chơi game',
        emoji: '🎮',
        question: 'Bạn nên phản ứng như thế nào?',
        options: [
          'Tạm dừng game và lắng nghe bạn nói',
          'Vừa chơi vừa nghe một cách敷衍',
          "Nói: 'Đợi tí, tôi đang bận'",
          'Làm ngơ và tiếp tục chơi',
        ],
        correct: 0,
        explanation:
          'Tập trung lắng nghe khi ai đó nói chuyện thể hiện sự tôn trọng.',
        tips: 'Lắng nghe là kỹ năng quan trọng nhất trong giao tiếp!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'comm_5',
        situation: 'Bạn không đồng ý với ý kiến của bạn bè',
        emoji: '🤨',
        question: 'Cách thể hiện bất đồng ý tốt nhất là gì?',
        options: [
          "Nói: 'Mình nghĩ khác, theo mình thì...'",
          "Nói: 'Bạn sai rồi!'",
          'Im lặng và không nói gì',
          'Cãi lại một cách gay gắt',
        ],
        correct: 0,
        explanation:
          'Thể hiện ý kiến khác một cách nhẹ nhàng giúp duy trì mối quan hệ tốt.',
        tips: 'Có thể không đồng ý nhưng vẫn tôn trọng ý kiến của người khác!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'comm_6',
        situation: 'Bạn muốn khen ngợi bài vẽ đẹp của bạn bè',
        emoji: '🎨',
        question: 'Cách khen hay nhất là gì?',
        options: [
          'Bài vẽ của bạn thật đẹp, mình thích màu sắc bạn chọn!',
          'Bài vẽ này ổn đấy',
          'Bài vẽ đẹp nhưng còn thiếu cái này cái kia',
          'Bài vẽ của mình đẹp hơn',
        ],
        correct: 0,
        explanation: 'Lời khen cụ thể và chân thành sẽ làm người khác vui hơn.',
        tips: 'Khen ngợi chân thành giúp củng cố tình bạn!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'comm_7',
        situation: 'Bạn vô tình làm đổ nước của bạn khác',
        emoji: '😰',
        question: 'Bạn nên làm gì ngay lập tức?',
        options: [
          'Nói xin lỗi và giúp lau dọn',
          'Bỏ chạy để tránh bị mắng',
          'Đổ lỗi cho người khác',
          'Giả vờ như không có chuyện gì',
        ],
        correct: 0,
        explanation:
          'Xin lỗi và khắc phục hậu quả thể hiện trách nhiệm và sự trưởng thành.',
        tips:
          'Thừa nhận lỗi lầm và sửa chữa là dấu hiệu của người trưởng thành!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'comm_8',
        situation: 'Bạn muốn mời bạn bè đến sinh nhật của mình',
        emoji: '🎂',
        question: 'Cách mời hay nhất là gì?',
        options: [
          'Mình sẽ tổ chức sinh nhật vào chủ nhật, bạn có thể đến không?',
          'Bạn phải đến sinh nhật mình nhé!',
          'Sinh nhật mình có nhiều quà, bạn đến nhé!',
          'Chỉ mời qua tin nhắn mà không nói trực tiếp',
        ],
        correct: 0,
        explanation:
          'Lời mời lịch sự và rõ ràng giúp bạn bè dễ dàng quyết định.',
        tips: 'Lời mời ấm áp sẽ khiến người khác cảm thấy được trân trọng!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'comm_9',
        situation: 'Bạn bè chia sẻ một tin buồn với bạn',
        emoji: '😢',
        question: 'Cách an ủi tốt nhất là gì?',
        options: [
          "Lắng nghe và nói: 'Mình hiểu cảm giác của bạn'",
          "Nói: 'Đừng buồn nữa, vui lên!'",
          'Kể chuyện vui để làm bạn quên đi',
          "Nói: 'Chuyện đó bình thường thôi'",
        ],
        correct: 0,
        explanation:
          'Thể hiện sự đồng cảm và lắng nghe là cách an ủi hiệu quả nhất.',
        tips: 'Đôi khi chỉ cần lắng nghe đã là cách giúp đỡ tốt nhất!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'comm_10',
        situation: 'Bạn muốn từ chối lời mời chơi của bạn bè vì có việc khác',
        emoji: '🤷',
        question: 'Cách từ chối lịch sự nhất là gì?',
        options: [
          'Cảm ơn bạn đã mời, nhưng hôm nay mình có việc rồi',
          'Mình không muốn chơi',
          'Mình bận rồi, hẹn lần khác nhé',
          'Không nói gì và tránh mặt',
        ],
        correct: 0,
        explanation:
          'Từ chối một cách lịch sự và giải thích lý do giúp duy trì tình bạn.',
        tips: 'Từ chối không có nghĩa là không quan tâm, hãy giải thích lý do!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'comm_11',
        situation: 'Bạn muốn góp ý để bạn bè cải thiện bài thuyết trình',
        emoji: '📝',
        question: 'Cách góp ý tích cực nhất là gì?',
        options: [
          'Bài thuyết trình hay đấy! Nếu thêm hình ảnh sẽ sinh động hơn',
          'Bài của bạn chưa hay lắm',
          'Mình nghĩ bạn nên làm lại từ đầu',
          'Bài ổn rồi, không cần sửa gì',
        ],
        correct: 0,
        explanation:
          'Góp ý tích cực bắt đầu bằng lời khen rồi đưa ra gợi ý cải thiện.',
        tips: "Góp ý kiểu 'sandwich': khen - góp ý - khuyến khích!",
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'comm_12',
        situation: 'Bạn gặp một bạn mới trong lớp',
        emoji: '👋',
        question: 'Cách làm quen tốt nhất là gì?',
        options: [
          'Chào bạn và tự giới thiệu tên mình',
          'Chờ bạn ấy chào mình trước',
          'Hỏi thăm về gia đình bạn ấy ngay',
          'Chỉ mỉm cười và không nói gì',
        ],
        correct: 0,
        explanation:
          'Chủ động chào hỏi và giới thiệu là cách tốt nhất để bắt đầu tình bạn.',
        tips: 'Nụ cười và lời chào ấm áp là chìa khóa mở đầu tình bạn!',
        difficulty: 1,
        ageGroup: '6-8',
      },
      {
        id: 'comm_13',
        situation: 'Bạn muốn xin phép cô giáo đi vệ sinh giữa giờ học',
        emoji: '🙋',
        question: 'Cách xin phép đúng cách là gì?',
        options: [
          "Giơ tay và nói: 'Cô ơi, em xin phép đi vệ sinh ạ'",
          'Đứng dậy và đi luôn',
          'Hỏi bạn bên cạnh có được đi không',
          'Chờ đến hết giờ học',
        ],
        correct: 0,
        explanation:
          'Xin phép một cách lịch sự thể hiện sự tôn trọng với giáo viên.',
        tips: 'Luôn xin phép trước khi làm điều gì đó trong lớp học!',
        difficulty: 1,
        ageGroup: '6-8',
      },
      {
        id: 'comm_14',
        situation: 'Bạn muốn mượn bút của bạn bè',
        emoji: '✏️',
        question: 'Cách xin mượn lịch sự nhất là gì?',
        options: [
          'Bạn ơi, mình có thể mượn bút được không?',
          'Cho mình mượn bút',
          'Lấy luôn bút mà không hỏi',
          'Mình mượn bút nhé',
        ],
        correct: 0,
        explanation:
          'Hỏi xin phép một cách lịch sự thể hiện sự tôn trọng tài sản của người khác.',
        tips: 'Luôn hỏi trước khi mượn đồ của người khác!',
        difficulty: 1,
        ageGroup: '6-8',
      },
      {
        id: 'comm_15',
        situation: 'Bạn muốn tham gia cuộc trò chuyện của nhóm bạn',
        emoji: '💭',
        question: 'Cách tham gia cuộc trò chuyện tự nhiên nhất là gì?',
        options: [
          "Chờ có khoảng lặng rồi nói: 'Mình cũng nghĩ vậy'",
          'Ngắt lời ngay khi có ý kiến',
          'Nói to để thu hút sự chú ý',
          'Đứng nghe mà không tham gia',
        ],
        correct: 0,
        explanation:
          'Chờ thời điểm thích hợp để tham gia thể hiện kỹ năng giao tiếp tốt.',
        tips: 'Biết lúc nào nên nói và lúc nào nên nghe là kỹ năng quan trọng!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'comm_16',
        situation: 'Bạn muốn cảm ơn cô giáo đã giúp đỡ mình',
        emoji: '🙏',
        question: 'Cách cảm ơn chân thành nhất là gì?',
        options: [
          'Cô ơi, em cảm ơn cô đã giúp em hiểu bài ạ',
          'Cảm ơn cô',
          'Viết thư cảm ơn dài dòng',
          'Mua quà tặng cô giáo',
        ],
        correct: 0,
        explanation:
          'Lời cảm ơn cụ thể và chân thành có ý nghĩa hơn những hành động phức tạp.',
        tips: 'Lời cảm ơn từ trái tim luôn có sức mạnh đặc biệt!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'comm_17',
        situation: 'Bạn muốn mời bạn bè chơi một trò chơi mới',
        emoji: '🎲',
        question: 'Cách mời chơi hấp dẫn nhất là gì?',
        options: [
          'Mình có một trò chơi hay, các bạn muốn thử không?',
          'Chúng ta phải chơi trò này',
          'Trò chơi này rất dễ, ai cũng chơi được',
          'Chỉ mời những bạn thân nhất',
        ],
        correct: 0,
        explanation: 'Lời mời hấp dẫn và để lại quyền lựa chọn cho người khác.',
        tips: 'Tạo sự tò mò và hứng thú sẽ khiến người khác muốn tham gia!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'comm_18',
        situation: 'Bạn muốn xin lỗi vì đã làm bạn bè buồn',
        emoji: '😔',
        question: 'Cách xin lỗi chân thành nhất là gì?',
        options: [
          'Mình xin lỗi vì đã làm bạn buồn, mình sẽ cẩn thận hơn',
          'Xin lỗi nhé',
          'Mình không cố ý đâu',
          'Bạn đừng buồn nữa',
        ],
        correct: 0,
        explanation:
          'Lời xin lỗi chân thành kèm theo cam kết thay đổi thể hiện sự trưởng thành.',
        tips:
          'Xin lỗi thật lòng và hứa sẽ cải thiện là cách tốt nhất để hàn gắn!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'comm_19',
        situation: 'Bạn muốn chia sẻ một tin vui với bạn bè',
        emoji: '🎉',
        question: 'Cách chia sẻ tin vui tốt nhất là gì?',
        options: [
          'Các bạn ơi, mình có tin vui muốn chia sẻ!',
          'Mình giỏi hơn các bạn rồi!',
          'Các bạn có biết mình vừa...',
          'Khoe khoang một cách phô trương',
        ],
        correct: 0,
        explanation:
          'Chia sẻ tin vui một cách khiêm tốn và vui vẻ sẽ được mọi người đón nhận.',
        tips:
          'Niềm vui được chia sẻ sẽ nhân đôi, hãy chia sẻ một cách khiêm tốn!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'comm_20',
        situation: 'Bạn muốn hỏi đường đến thư viện',
        emoji: '📍',
        question: 'Cách hỏi đường lịch sự nhất là gì?',
        options: [
          'Xin chào, bạn có thể chỉ đường đến thư viện được không ạ?',
          'Thư viện ở đâu vậy?',
          'Bạn biết đường đến thư viện không?',
          'Chỉ đường đến thư viện cho mình',
        ],
        correct: 0,
        explanation:
          'Chào hỏi và hỏi một cách lịch sự thể hiện sự tôn trọng với người lạ.',
        tips:
          'Lời chào và lời cảm ơn luôn làm cho giao tiếp trở nên dễ chịu hơn!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'comm_21',
        situation: 'Bạn muốn kết thúc cuộc trò chuyện để về nhà',
        emoji: '👋',
        question: 'Cách kết thúc cuộc trò chuyện lịch sự nhất là gì?',
        options: [
          'Mình phải về nhà rồi, hẹn gặp lại các bạn nhé!',
          'Mình đi đây',
          'Tạm biệt',
          'Bỏ đi mà không nói gì',
        ],
        correct: 0,
        explanation:
          'Giải thích lý do và chào tạm biệt ấm áp thể hiện sự tôn trọng.',
        tips: 'Kết thúc cuộc trò chuyện một cách ấm áp sẽ để lại ấn tượng tốt!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'comm_22',
        situation: 'Bạn muốn giới thiệu hai người bạn với nhau',
        emoji: '🤝',
        question: 'Cách giới thiệu tốt nhất là gì?',
        options: [
          'An ơi, đây là Bình - bạn cùng lớp mình. Bình ơi, đây là An',
          'Đây là An, đây là Bình',
          'Các bạn tự làm quen nhau nhé',
          'Chỉ nói tên mà không giải thích gì',
        ],
        correct: 0,
        explanation:
          'Giới thiệu rõ ràng và cung cấp thông tin giúp hai người dễ bắt chuyện.',
        tips:
          'Giới thiệu chi tiết giúp mọi người dễ dàng bắt đầu cuộc trò chuyện!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'comm_23',
        situation: 'Bạn muốn nhờ bạn bè giúp đỡ làm bài tập',
        emoji: '📚',
        question: 'Cách nhờ giúp đỡ phù hợp nhất là gì?',
        options: [
          'Bạn có thể giúp mình giải thích bài này được không?',
          'Làm bài này giúp mình',
          'Mình không biết làm, bạn làm giúp',
          'Cho mình chép bài của bạn',
        ],
        correct: 0,
        explanation:
          'Nhờ giúp đỡ để hiểu bài thể hiện mong muốn học hỏi, không phải ỷ lại.',
        tips: 'Nhờ giúp đỡ để học, không phải để ỷ lại người khác!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'comm_24',
        situation: 'Bạn muốn bày tỏ sự không đồng ý với quyết định của nhóm',
        emoji: '🤔',
        question: 'Cách bày tỏ ý kiến tốt nhất là gì?',
        options: [
          'Mình hiểu ý kiến của các bạn, nhưng mình nghĩ nên thử cách khác',
          'Các bạn sai rồi',
          'Mình không đồng ý',
          'Im lặng và làm theo miễn cưỡng',
        ],
        correct: 0,
        explanation:
          'Thể hiện sự tôn trọng ý kiến khác trước khi đưa ra quan điểm của mình.',
        tips: 'Có thể không đồng ý nhưng vẫn tôn trọng và lịch sự!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'comm_25',
        situation: 'Bạn muốn mời cả lớp đến buổi tiệc của mình',
        emoji: '🎊',
        question: 'Cách mời cả lớp tốt nhất là gì?',
        options: [
          'Thầy cô và các bạn ơi, mình muốn mời mọi người đến tiệc sinh nhật',
          'Ai muốn đến tiệc mình thì đến',
          'Chỉ mời một số bạn thân',
          'Gửi thiệp mời cho từng người một',
        ],
        correct: 0,
        explanation:
          'Mời công khai và ấm áp giúp mọi người cảm thấy được chào đón.',
        tips:
          'Lời mời chân thành và bao gồm tất cả sẽ tạo ra bầu không khí tích cực!',
        difficulty: 3,
        ageGroup: '9-10',
      },
    ],
  },
  {
    id: 'emotion',
    title: 'Cảm Xúc',
    description: 'Hiểu và quản lý cảm xúc của mình',
    icon: '😊',
    difficulty: 2,
    questions: [
      {
        id: 'emo_1',
        situation: 'Bạn cảm thấy tức giận vì bạn bè không chơi với mình',
        emoji: '😠',
        question: 'Cách tốt nhất để xử lý cảm xúc này là gì?',
        options: [
          'Hít thở sâu và nói chuyện với bạn bè',
          'La hét và đánh bạn bè',
          'Khóc và chạy về nhà',
          'Giả vờ không quan tâm',
        ],
        correct: 0,
        explanation:
          'Hít thở sâu giúp bình tĩnh và nói chuyện giúp giải quyết vấn đề.',
        tips: 'Khi tức giận, hãy đếm từ 1 đến 10 trước khi hành động!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'emo_2',
        situation:
          'Bạn cảm thấy buồn vì không được điểm cao trong bài kiểm tra',
        emoji: '😢',
        question: 'Cách tốt nhất để đối phó với nỗi buồn này là gì?',
        options: [
          'Chấp nhận cảm xúc và tìm cách cải thiện lần sau',
          'Khóc suốt ngày',
          'Đổ lỗi cho giáo viên',
          'Bỏ cuộc và không cố gắng nữa',
        ],
        correct: 0,
        explanation:
          'Chấp nhận cảm xúc và học hỏi từ thất bại giúp bạn trưởng thành.',
        tips: 'Thất bại là cơ hội để học hỏi và cải thiện bản thân!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'emo_3',
        situation: 'Bạn cảm thấy lo lắng trước khi thuyết trình',
        emoji: '😰',
        question: 'Cách giảm lo lắng hiệu quả nhất là gì?',
        options: [
          'Chuẩn bị kỹ và thực hành nhiều lần',
          'Tránh né không thuyết trình',
          'Lo lắng suốt đêm không ngủ được',
          'Hy vọng sẽ không bị gọi',
        ],
        correct: 0,
        explanation:
          'Chuẩn bị tốt là cách tốt nhất để giảm lo lắng và tăng tự tin.',
        tips: 'Chuẩn bị kỹ càng sẽ giúp bạn tự tin hơn!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'emo_4',
        situation: 'Bạn cảm thấy ghen tị vì bạn bè có đồ chơi mới đẹp',
        emoji: '😒',
        question: 'Cách xử lý cảm xúc ghen tị tốt nhất là gì?',
        options: [
          'Nhận ra cảm xúc và tập trung vào những gì mình có',
          'Nói xấu đồ chơi của bạn',
          'Đòi bố mẹ mua đồ chơi giống vậy',
          'Tránh xa bạn ấy',
        ],
        correct: 0,
        explanation:
          'Nhận diện cảm xúc và biết ơn những gì mình có giúp vượt qua ghen tị.',
        tips: 'Hãy vui vẻ với những gì bạn có thay vì ghen tị với người khác!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'emo_5',
        situation: 'Bạn cảm thấy hạnh phúc vì được khen ngợi',
        emoji: '😊',
        question: 'Cách thể hiện niềm vui phù hợp nhất là gì?',
        options: [
          'Cảm ơn và chia sẻ niềm vui một cách khiêm tốn',
          'Khoe khoang với mọi người',
          'Cảm thấy mình giỏi hơn người khác',
          'Giấu niềm vui để tránh ghen tị',
        ],
        correct: 0,
        explanation:
          'Thể hiện niềm vui một cách khiêm tốn và biết ơn là cách tốt nhất.',
        tips: 'Niềm vui được chia sẻ sẽ nhân đôi!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'emo_6',
        situation: 'Bạn cảm thấy sợ hãi khi phải ngủ một mình',
        emoji: '😨',
        question: 'Cách đối phó với nỗi sợ tốt nhất là gì?',
        options: [
          'Nói chuyện với bố mẹ về nỗi sợ và tìm cách giải quyết',
          'Cố gắng ngủ mà không nói với ai',
          'Khóc cho đến khi có người đến',
          'Thức suốt đêm',
        ],
        correct: 0,
        explanation:
          'Chia sẻ nỗi sợ với người lớn giúp tìm ra giải pháp phù hợp.',
        tips: 'Đừng ngại chia sẻ nỗi sợ với người thân, họ sẽ giúp bạn!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'emo_7',
        situation: 'Bạn cảm thấy thất vọng vì không được chọn vào đội bóng',
        emoji: '😞',
        question: 'Cách xử lý thất vọng tích cực nhất là gì?',
        options: [
          'Chấp nhận kết quả và tập luyện chăm chỉ hơn',
          'Tức giận và bỏ cuộc',
          'Đổ lỗi cho huấn luyện viên',
          'Nói xấu những bạn được chọn',
        ],
        correct: 0,
        explanation: 'Chấp nhận thất vọng và biến nó thành động lực cải thiện.',
        tips: 'Thất vọng có thể trở thành động lực mạnh mẽ để cố gắng hơn!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'emo_8',
        situation: 'Bạn cảm thấy xấu hổ vì đã trả lời sai trước lớp',
        emoji: '😳',
        question: 'Cách đối phó với cảm giác xấu hổ tốt nhất là gì?',
        options: [
          'Nhận ra rằng mọi người đều có thể mắc lỗi',
          'Giấu mặt và không muốn nói chuyện với ai',
          'Tức giận với bản thân',
          'Quyết định không bao giờ phát biểu nữa',
        ],
        correct: 0,
        explanation:
          'Hiểu rằng mắc lỗi là điều bình thường giúp vượt qua cảm giác xấu hổ.',
        tips: 'Mọi người đều mắc lỗi, điều quan trọng là học hỏi từ lỗi lầm!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'emo_9',
        situation: 'Bạn cảm thấy cô đơn vì không có ai chơi cùng',
        emoji: '😔',
        question: 'Cách tốt nhất để đối phó với cô đơn là gì?',
        options: [
          'Chủ động tiếp cận và làm quen với bạn bè mới',
          'Ngồi một mình và buồn bã',
          'Đổ lỗi cho người khác',
          'Giả vờ không cần bạn bè',
        ],
        correct: 0,
        explanation: 'Chủ động kết bạn là cách tốt nhất để vượt qua cô đơn.',
        tips:
          'Hãy mở lòng và chủ động kết bạn, bạn sẽ tìm được những người bạn tốt!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'emo_10',
        situation: 'Bạn cảm thấy hứng thú với một hoạt động mới',
        emoji: '🤩',
        question: 'Cách thể hiện sự hứng thú tích cực nhất là gì?',
        options: [
          'Tham gia tích cực và học hỏi nhiều điều mới',
          'Chỉ quan sát mà không tham gia',
          'So sánh với những hoạt động khác',
          'Nhanh chóng chán nản',
        ],
        correct: 0,
        explanation:
          'Tham gia tích cực giúp bạn tận dụng tối đa cơ hội học hỏi.',
        tips: 'Sự hứng thú là động lực tuyệt vời để học những điều mới!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'emo_11',
        situation: 'Bạn cảm thấy stress vì có quá nhiều bài tập',
        emoji: '😵',
        question: 'Cách quản lý stress hiệu quả nhất là gì?',
        options: [
          'Lập kế hoạch và chia nhỏ công việc',
          'Hoảng loạn và không biết làm gì',
          'Bỏ qua tất cả bài tập',
          'Thức đêm để làm hết một lúc',
        ],
        correct: 0,
        explanation:
          'Lập kế hoạch và chia nhỏ công việc giúp giảm stress hiệu quả.',
        tips: 'Chia nhỏ công việc lớn thành những việc nhỏ dễ làm hơn!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'emo_12',
        situation: 'Bạn cảm thấy tự hào về thành tích của mình',
        emoji: '😌',
        question: 'Cách thể hiện sự tự hào phù hợp nhất là gì?',
        options: [
          'Cảm ơn những người đã giúp đỡ và tiếp tục cố gắng',
          'Khoe khoang với mọi người',
          'Cảm thấy mình không cần cố gắng nữa',
          'So sánh với người khác',
        ],
        correct: 0,
        explanation:
          'Tự hào một cách khiêm tốn và biết ơn là thái độ tích cực.',
        tips: 'Hãy tự hào nhưng vẫn khiêm tốn và biết ơn!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'emo_13',
        situation: 'Bạn cảm thấy bối rối khi không hiểu bài học',
        emoji: '😕',
        question: 'Cách xử lý sự bối rối tốt nhất là gì?',
        options: [
          'Hỏi giáo viên hoặc bạn bè để được giải thích',
          'Giả vờ hiểu để tránh xấu hổ',
          'Bỏ qua và hy vọng sẽ hiểu sau',
          'Tức giận vì không hiểu',
        ],
        correct: 0,
        explanation: 'Hỏi khi chưa hiểu là cách tốt nhất để học tập hiệu quả.',
        tips: 'Đừng ngại hỏi khi chưa hiểu, đó là cách học tập thông minh!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'emo_14',
        situation: 'Bạn cảm thấy phấn khích vì sắp đi du lịch',
        emoji: '🤗',
        question: 'Cách thể hiện sự phấn khích phù hợp nhất là gì?',
        options: [
          'Chia sẻ niềm vui và chuẩn bị kỹ càng cho chuyến đi',
          'Quá phấn khích đến mức không thể tập trung học tập',
          'Khoe khoang với những bạn không được đi',
          'Giấu niềm vui để tránh ghen tị',
        ],
        correct: 0,
        explanation:
          'Chia sẻ niềm vui một cách tích cực và chuẩn bị tốt cho hoạt động.',
        tips: 'Niềm vui được chia sẻ sẽ tăng gấp đôi!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'emo_15',
        situation: 'Bạn cảm thấy mệt mỏi sau một ngày học tập căng thẳng',
        emoji: '😴',
        question: 'Cách tốt nhất để phục hồi năng lượng là gì?',
        options: [
          'Nghỉ ngơi đầy đủ và làm những việc mình thích',
          'Tiếp tục học thêm để không bị tụt lại',
          'Xem TV suốt đêm',
          'Ăn nhiều đồ ngọt để có năng lượng',
        ],
        correct: 0,
        explanation:
          'Nghỉ ngơi hợp lý và thư giãn giúp phục hồi năng lượng hiệu quả.',
        tips: 'Cơ thể và tâm trí cần được nghỉ ngơi để hoạt động tốt!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'emo_16',
        situation: 'Bạn cảm thấy tức giận vì bị đổ lỗi oan',
        emoji: '😡',
        question: 'Cách xử lý cơn tức giận này tốt nhất là gì?',
        options: [
          'Bình tĩnh giải thích sự thật một cách rõ ràng',
          'La hét và cãi lại gay gắt',
          'Im lặng và nuốt giận',
          'Trả thù bằng cách đổ lỗi lại',
        ],
        correct: 0,
        explanation:
          'Giữ bình tĩnh và giải thích sự thật là cách tốt nhất để giải quyết hiểu lầm.',
        tips: 'Sự thật sẽ tỏa sáng khi bạn trình bày một cách bình tĩnh!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'emo_17',
        situation: 'Bạn cảm thấy ngạc nhiên khi nhận được món quà bất ngờ',
        emoji: '😲',
        question: 'Cách thể hiện sự ngạc nhiên tích cực nhất là gì?',
        options: [
          'Cảm ơn chân thành và thể hiện niềm vui',
          'Hỏi tại sao lại tặng quà',
          'So sánh với những món quà khác',
          'Giấu cảm xúc để tỏ ra bình thường',
        ],
        correct: 0,
        explanation:
          'Thể hiện lòng biết ơn và niềm vui chân thành khi nhận quà.',
        tips: 'Lòng biết ơn chân thành là món quà tốt nhất bạn có thể đáp lại!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'emo_18',
        situation: 'Bạn cảm thấy lo lắng về tương lai',
        emoji: '😟',
        question: 'Cách đối phó với lo lắng về tương lai tốt nhất là gì?',
        options: [
          'Tập trung vào hiện tại và chuẩn bị tốt cho tương lai',
          'Lo lắng suốt ngày về những điều chưa xảy ra',
          'Tránh nghĩ về tương lai',
          'Hy vọng mọi thứ sẽ tự khắc phục',
        ],
        correct: 0,
        explanation:
          'Tập trung vào hiện tại và chuẩn bị tích cực cho tương lai.',
        tips: 'Tương lai được xây dựng từ những hành động tốt ở hiện tại!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'emo_19',
        situation: 'Bạn cảm thấy bực bội vì phải chờ đợi lâu',
        emoji: '😤',
        question: 'Cách xử lý sự bực bội khi chờ đợi tốt nhất là gì?',
        options: [
          'Tìm việc gì đó để làm trong lúc chờ',
          'Than phiền liên tục',
          'Tức giận và bỏ đi',
          'Đứng im và cảm thấy khó chịu',
        ],
        correct: 0,
        explanation:
          'Tận dụng thời gian chờ đợi để làm việc hữu ích giúp giảm bực bội.',
        tips: 'Biến thời gian chờ đợi thành cơ hội để làm điều gì đó có ích!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'emo_20',
        situation: 'Bạn cảm thấy hạnh phúc khi giúp đỡ được người khác',
        emoji: '🥰',
        question: 'Cách duy trì cảm giác hạnh phúc này tốt nhất là gì?',
        options: [
          'Tiếp tục giúp đỡ người khác khi có thể',
          'Khoe khoang về việc mình đã giúp đỡ',
          'Chờ đợi lời cảm ơn từ người được giúp',
          'Cảm thấy mình giỏi hơn người khác',
        ],
        correct: 0,
        explanation: 'Tiếp tục làm việc tốt sẽ mang lại hạnh phúc bền vững.',
        tips: 'Hạnh phúc thật sự đến từ việc giúp đỡ người khác!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'emo_21',
        situation: 'Bạn cảm thấy nhớ nhà khi đi cắm trại',
        emoji: '🏠',
        question: 'Cách xử lý cảm giác nhớ nhà tốt nhất là gì?',
        options: [
          'Tham gia các hoạt động và kết bạn với mọi người',
          'Khóc và đòi về nhà',
          'Ngồi một mình và buồn bã',
          'Gọi điện về nhà liên tục',
        ],
        correct: 0,
        explanation: 'Tham gia hoạt động tích cực giúp giảm cảm giác nhớ nhà.',
        tips: 'Tạo ra những kỷ niệm mới sẽ giúp bạn vượt qua cảm giác nhớ nhà!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'emo_22',
        situation: 'Bạn cảm thấy tự tin sau khi hoàn thành một thử thách khó',
        emoji: '💪',
        question: 'Cách duy trì sự tự tin tích cực nhất là gì?',
        options: [
          'Đặt ra những thử thách mới phù hợp với khả năng',
          'Nghĩ rằng mình giỏi nhất',
          'Ngừng thử thách để tránh thất bại',
          'So sánh với người khác',
        ],
        correct: 0,
        explanation:
          'Tiếp tục thử thách bản thân một cách hợp lý giúp duy trì tự tin.',
        tips: 'Tự tin được xây dựng qua từng thành công nhỏ!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'emo_23',
        situation: 'Bạn cảm thấy áp lực vì kỳ vọng của bố mẹ',
        emoji: '😰',
        question: 'Cách xử lý áp lực này tốt nhất là gì?',
        options: [
          'Nói chuyện thẳng thắn với bố mẹ về cảm xúc của mình',
          'Giấu cảm xúc và cố gắng đáp ứng mọi kỳ vọng',
          'Tức giận và phản kháng',
          'Bỏ cuộc và không cố gắng',
        ],
        correct: 0,
        explanation:
          'Giao tiếp mở với bố mẹ giúp họ hiểu và điều chỉnh kỳ vọng phù hợp.',
        tips: 'Bố mẹ sẽ hiểu bạn hơn khi bạn chia sẻ cảm xúc thật!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'emo_24',
        situation: 'Bạn cảm thấy vui vẻ khi chơi với bạn bè',
        emoji: '😄',
        question: 'Cách tận hưởng niềm vui tốt nhất là gì?',
        options: [
          'Sống trọn vẹn trong khoảnh khắc và tạo kỷ niệm đẹp',
          'Lo lắng về việc niềm vui sẽ kết thúc',
          'So sánh với những lần vui khác',
          'Cố gắng kéo dài niềm vui một cách cưỡng ép',
        ],
        correct: 0,
        explanation:
          'Tận hưởng trọn vẹn khoảnh khắc hiện tại mang lại hạnh phúc thật sự.',
        tips: 'Những khoảnh khắc vui vẻ cần được trân trọng và tận hưởng!',
        difficulty: 2,
        ageGroup: '6-8',
      },
      {
        id: 'emo_25',
        situation: 'Bạn cảm thấy thất vọng khi kế hoạch bị hủy bỏ',
        emoji: '😞',
        question: 'Cách đối phó với thất vọng này tốt nhất là gì?',
        options: [
          'Chấp nhận thay đổi và tìm hoạt động thay thế thú vị',
          'Tức giận và đổ lỗi cho mọi người',
          'Buồn bã suốt ngày',
          'Quyết định không bao giờ lập kế hoạch nữa',
        ],
        correct: 0,
        explanation: 'Linh hoạt thích ứng với thay đổi và tìm cơ hội mới.',
        tips: 'Đôi khi những thay đổi bất ngờ lại mang đến cơ hội tốt hơn!',
        difficulty: 3,
        ageGroup: '9-10',
      },
    ],
  },
  // Tiếp tục với các chủ đề khác...
  {
    id: 'teamwork',
    title: 'Làm Việc Nhóm',
    description: 'Hợp tác và chia sẻ với bạn bè',
    icon: '🤝',
    difficulty: 3,
    questions: [
      {
        id: 'team_1',
        situation: 'Nhóm bạn đang làm dự án nhưng có bạn không tham gia',
        emoji: '🤝',
        question: 'Bạn sẽ làm gì?',
        options: [
          'Khuyến khích và giúp đỡ bạn ấy tham gia',
          'Bỏ qua và làm một mình',
          'Báo cáo với cô giáo ngay lập tức',
          'Nói xấu bạn ấy với những người khác',
        ],
        correct: 0,
        explanation: 'Khuyến khích và giúp đỡ thể hiện tinh thần đồng đội tốt.',
        tips: 'Làm việc nhóm hiệu quả khi mọi người đều được tham gia!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'team_2',
        situation: 'Trong nhóm, bạn có ý tưởng khác với đa số',
        emoji: '💡',
        question: 'Bạn nên làm gì với ý tưởng của mình?',
        options: [
          'Trình bày ý tưởng một cách rõ ràng và lắng nghe phản hồi',
          'Giữ im lặng vì sợ bị phản đối',
          'Cố gắng thuyết phục mọi người bằng mọi cách',
          'Tức giận vì không ai đồng ý',
        ],
        correct: 0,
        explanation:
          'Chia sẻ ý tưởng một cách tôn trọng giúp nhóm có thêm lựa chọn.',
        tips: 'Ý tưởng hay cần được chia sẻ để nhóm cùng phát triển!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'team_3',
        situation: 'Một thành viên trong nhóm làm việc chậm hơn mọi người',
        emoji: '🐌',
        question: 'Cách tốt nhất để giúp đỡ bạn ấy là gì?',
        options: [
          'Hỏi xem bạn ấy cần giúp gì và hỗ trợ tận tình',
          'Làm thay công việc của bạn ấy',
          'Phàn nàn về tốc độ làm việc của bạn ấy',
          'Đề nghị loại bạn ấy khỏi nhóm',
        ],
        correct: 0,
        explanation:
          'Hỗ trợ và giúp đỡ thành viên khó khăn thể hiện tinh thần đồng đội.',
        tips: 'Nhóm mạnh khi mọi thành viên đều được hỗ trợ!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'team_4',
        situation: 'Nhóm bạn gặp khó khăn trong việc phân chia công việc',
        emoji: '📋',
        question: 'Cách giải quyết tốt nhất là gì?',
        options: [
          'Thảo luận về sở thích và khả năng của từng người',
          'Để một người quyết định tất cả',
          'Chia đều công việc mà không quan tâm khả năng',
          'Cãi nhau cho đến khi có kết quả',
        ],
        correct: 0,
        explanation:
          'Phân chia công việc dựa trên khả năng giúp nhóm hiệu quả hơn.',
        tips: 'Mỗi người có điểm mạnh riêng, hãy tận dụng!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'team_5',
        situation: 'Nhóm bạn có ý kiến khác nhau về cách thực hiện dự án',
        emoji: '🤔',
        question: 'Cách tốt nhất để đi đến thống nhất là gì?',
        options: [
          'Lắng nghe tất cả ý kiến và tìm điểm chung',
          'Bỏ phiếu và làm theo ý kiến đa số',
          'Để nhóm trưởng quyết định',
          'Mỗi người làm theo ý mình',
        ],
        correct: 0,
        explanation:
          'Lắng nghe và tìm điểm chung giúp tạo ra giải pháp tốt nhất.',
        tips: 'Ý kiến khác nhau có thể tạo ra giải pháp sáng tạo!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'team_6',
        situation: 'Một bạn trong nhóm không đồng ý với ý kiến của bạn',
        emoji: '🗣️',
        question: 'Bạn sẽ phản ứng thế nào?',
        options: [
          'Lắng nghe và trao đổi để hiểu quan điểm của bạn ấy',
          'Cố gắng cãi cho bằng được',
          'Bỏ nhóm vì không ai ủng hộ',
          'Giận dỗi và không nói chuyện nữa',
        ],
        correct: 0,
        explanation: 'Biết lắng nghe và trao đổi giúp nhóm hiểu nhau hơn.',
        tips: 'Lắng nghe là chìa khóa để hợp tác hiệu quả!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'team_7',
        situation: 'Bạn có thể hoàn thành công việc nhanh hơn nếu làm một mình',
        emoji: '⚡',
        question: 'Bạn nên làm gì?',
        options: [
          'Tiếp tục làm việc nhóm để mọi người cùng học hỏi',
          'Tự làm hết phần của nhóm để nhanh hơn',
          'Chê bai bạn bè vì làm chậm',
          'Yêu cầu cô giáo đổi nhóm',
        ],
        correct: 0,
        explanation: 'Làm việc nhóm giúp mọi người cùng tiến bộ.',
        tips: 'Kết quả tốt hơn khi cả nhóm đều tham gia!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'team_8',
        situation: 'Nhóm bạn có một thành viên rất giỏi',
        emoji: '⭐',
        question: 'Bạn nên làm gì khi làm việc với bạn ấy?',
        options: [
          'Học hỏi và cùng đóng góp ý kiến',
          'Phó mặc cho bạn ấy làm hết',
          'Không đưa ý tưởng vì nghĩ mình kém hơn',
          'Cố tình làm khác để thể hiện',
        ],
        correct: 0,
        explanation: 'Học hỏi và cùng đóng góp giúp nhóm phát triển toàn diện.',
        tips: 'Mỗi thành viên đều có giá trị riêng trong nhóm!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'team_9',
        situation:
          'Trong nhóm, có người thường xuyên nói nhiều và không để ai khác phát biểu',
        emoji: '🔊',
        question: 'Bạn nên làm gì?',
        options: [
          'Lịch sự nhắc nhở và tạo cơ hội cho mọi người',
          'Ngồi im và để bạn ấy nói mãi',
          'Giận dỗi và không tham gia nữa',
          'Cắt ngang một cách thô lỗ',
        ],
        correct: 0,
        explanation: 'Khéo léo nhắc nhở giúp nhóm cân bằng ý kiến.',
        tips: 'Ai cũng xứng đáng được lắng nghe!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'team_10',
        situation: 'Nhóm bạn hoàn thành công việc sớm hơn dự kiến',
        emoji: '⏰',
        question: 'Nhóm nên làm gì tiếp theo?',
        options: [
          'Xem lại và chỉnh sửa để hoàn thiện hơn',
          'Ngừng làm và chơi thôi',
          'Chia nhỏ nhóm để làm thêm việc khác',
          'Để nguyên vì làm xong rồi',
        ],
        correct: 0,
        explanation: 'Kiểm tra lại công việc giúp kết quả tốt nhất.',
        tips: 'Chất lượng quan trọng hơn tốc độ!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'team_11',
        situation:
          'Một thành viên thường xuyên đi muộn trong các buổi làm nhóm',
        emoji: '⌛',
        question: 'Bạn nên xử lý như thế nào?',
        options: [
          'Trao đổi riêng và tìm hiểu lý do',
          'Nói xấu bạn ấy với cả nhóm',
          'Phớt lờ và để mặc',
          'Báo ngay với cô giáo mà không nói với bạn ấy',
        ],
        correct: 0,
        explanation: 'Trao đổi trực tiếp thể hiện sự tôn trọng và quan tâm.',
        tips: 'Giao tiếp là cách tốt nhất để giải quyết vấn đề!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'team_12',
        situation: 'Cả nhóm đang bế tắc, chưa nghĩ ra ý tưởng nào',
        emoji: '🤯',
        question: 'Bạn sẽ làm gì để giúp nhóm?',
        options: [
          'Đề xuất trò chơi nhỏ hoặc nghỉ ngắn để lấy lại tinh thần',
          'Bỏ về vì chán nản',
          'Ngồi im chờ người khác nghĩ',
          'Chỉ trích nhóm vì thiếu ý tưởng',
        ],
        correct: 0,
        explanation: 'Đổi không khí giúp nhóm sáng tạo hơn.',
        tips: 'Tinh thần thoải mái giúp ý tưởng dễ nảy sinh!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'team_13',
        situation: 'Có bạn trong nhóm không hiểu nhiệm vụ',
        emoji: '📖',
        question: 'Bạn nên làm gì?',
        options: [
          'Giải thích lại và cùng bạn ấy thực hành',
          'Bỏ qua và để bạn ấy tự xoay xở',
          'Phàn nàn vì bạn ấy chậm hiểu',
          'Làm thay luôn phần việc',
        ],
        correct: 0,
        explanation: 'Giúp bạn hiểu sẽ làm cả nhóm mạnh hơn.',
        tips: 'Chia sẻ kiến thức là cách học tốt nhất!',
        difficulty: 3,
        ageGroup: '9-10',
      },
      {
        id: 'team_14',
        situation: 'Một thành viên có ý tưởng hay nhưng lại ngại chia sẻ',
        emoji: '🙊',
        question: 'Bạn sẽ làm gì?',
        options: [
          'Khuyến khích bạn ấy nói ra ý tưởng',
          'Cười nhạo vì bạn ấy rụt rè',
          'Phớt lờ và tiếp tục bàn bạc',
          'Nói thay bạn ấy mà không hỏi',
        ],
        correct: 0,
        explanation: 'Khuyến khích sẽ giúp bạn ấy tự tin hơn.',
        tips: 'Môi trường an toàn giúp ý tưởng được chia sẻ nhiều hơn!',
        difficulty: 4,
        ageGroup: '11-12',
      },
      {
        id: 'team_15',
        situation: 'Nhóm đã hoàn thành dự án thành công',
        emoji: '🎉',
        question: 'Bạn nên làm gì để kết thúc?',
        options: [
          'Cùng cả nhóm ăn mừng và cảm ơn nhau',
          'Tự nhận công lao về mình',
          'Không nói gì vì dự án xong rồi',
          'Chỉ khen bản thân vì làm tốt',
        ],
        correct: 0,
        explanation: 'Ăn mừng và cảm ơn nhau giúp gắn kết tình bạn.',
        tips: 'Thành công là của cả nhóm, hãy cùng chia sẻ!',
        difficulty: 3,
        ageGroup: '9-10',
      },
    ],
  },
  // Tiếp tục với các chủ đề khác: problem-solving, confidence, empathy...
];
