import type { QuizQuestion } from './QuizModal';

/**
 * Gợi ý: reward tăng nhẹ theo level
 * - MATH: atk + iq
 * - SOCIAL: empathy + hp
 */

export const MATH_QUESTIONS: QuizQuestion[] = [
  // ===== LEVEL 1 (cơ bản) =====
  {
    id: 'm1',
    type: 'MATH',
    level: 1,
    subType: 'CALC',
    title: '🧠 Lớp học: Tính nhanh',
    question: '15 + 7 = ?',
    options: ['21', '22', '23'],
    answer: '22',
    reward: { atk: 2, iq: 1 },
  },
  {
    id: 'm2',
    type: 'MATH',
    level: 1,
    subType: 'CALC',
    title: '🧠 Thư viện: Chia đều',
    question: '36 ÷ 6 = ?',
    options: ['5', '6', '7'],
    answer: '6',
    reward: { atk: 2, iq: 1 },
  },
  {
    id: 'm3',
    type: 'MATH',
    level: 1,
    subType: 'CALC',
    title: '🧠 Công viên: Nhẩm nhanh',
    question: '9 + 8 = ?',
    options: ['16', '17', '18'],
    answer: '17',
    reward: { atk: 2, iq: 1 },
  },
  {
    id: 'm4',
    type: 'MATH',
    level: 1,
    subType: 'CALC',
    title: '🧠 Ngã tư: Trừ nhanh',
    question: '25 - 9 = ?',
    options: ['14', '16', '18'],
    answer: '16',
    reward: { atk: 2, iq: 1 },
  },

  // ===== LEVEL 2 (dãy số / so sánh / bảng cửu chương) =====
  {
    id: 'm5',
    type: 'MATH',
    level: 2,
    subType: 'SEQUENCE',
    title: '🧠 Công viên: Dãy số',
    question: 'Điền số tiếp theo: 3, 6, 9, 12, ?',
    options: ['14', '15', '18'],
    answer: '15',
    reward: { atk: 3, iq: 1 },
  },
  {
    id: 'm6',
    type: 'MATH',
    level: 2,
    subType: 'LOGIC',
    title: '🧠 Ngã tư: So sánh',
    question: 'Số nào lớn hơn?',
    options: ['19', '91', 'bằng nhau'],
    answer: '91',
    reward: { atk: 2, iq: 2 },
  },
  {
    id: 'm7',
    type: 'MATH',
    level: 2,
    subType: 'CALC',
    title: '🧠 Lớp học: Nhân nhanh',
    question: '7 × 6 = ?',
    options: ['36', '42', '48'],
    answer: '42',
    reward: { atk: 3, iq: 1 },
  },
  {
    id: 'm8',
    type: 'MATH',
    level: 2,
    subType: 'SEQUENCE',
    title: '🧠 Thư viện: Dãy số nhảy 2',
    question: 'Điền số tiếp theo: 2, 4, 6, 8, ?',
    options: ['9', '10', '12'],
    answer: '10',
    reward: { atk: 3, iq: 1 },
  },

  // ===== LEVEL 3 (bài toán thực tế + logic) =====
  {
    id: 'm9',
    type: 'MATH',
    level: 3,
    subType: 'WORD_PROBLEM',
    title: '🧠 Lớp học: Bài toán thực tế',
    question:
      'Bạn có 20 kẹo, cho bạn 7 kẹo. Sau đó mua thêm 5 kẹo. Bạn có bao nhiêu kẹo?',
    options: ['18', '19', '20'],
    answer: '18',
    reward: { atk: 3, iq: 2 },
  },
  {
    id: 'm10',
    type: 'MATH',
    level: 3,
    subType: 'WORD_PROBLEM',
    title: '🧠 Công viên: Mua đồ',
    question:
      'Bạn có 30.000đ, mua bánh 12.000đ và sữa 10.000đ. Bạn còn lại bao nhiêu?',
    options: ['6.000đ', '8.000đ', '10.000đ'],
    answer: '8.000đ',
    reward: { atk: 3, iq: 2 },
  },
  {
    id: 'm11',
    type: 'MATH',
    level: 3,
    subType: 'LOGIC',
    title: '🧠 Thư viện: Suy luận',
    question: 'Nếu 2 + 2 = 4, 3 + 3 = 6 thì 4 + 4 = ?',
    options: ['6', '8', '10'],
    answer: '8',
    reward: { atk: 3, iq: 2 },
  },
  {
    id: 'm12',
    type: 'MATH',
    level: 3,
    subType: 'CALC',
    title: '🧠 Ngã tư: Tính ngược',
    question: 'Số nào cần cộng thêm 9 để được 25?',
    options: ['14', '16', '18'],
    answer: '16',
    reward: { atk: 3, iq: 2 },
  },

  // ===== LEVEL 4 (phân số đơn giản + suy luận 1 bước) =====
  {
    id: 'm13',
    type: 'MATH',
    level: 4,
    subType: 'FRACTION',
    title: '🧠 Thư viện: Phân số',
    question: '1/2 của 20 là bao nhiêu?',
    options: ['8', '10', '12'],
    answer: '10',
    reward: { atk: 4, iq: 3 },
  },
  {
    id: 'm14',
    type: 'MATH',
    level: 4,
    subType: 'LOGIC',
    title: '🧠 Công viên: Suy luận nhanh',
    question: 'Nếu 5 bạn mỗi bạn có 3 viên bi, tổng cộng có bao nhiêu viên bi?',
    options: ['12', '15', '18'],
    answer: '15',
    reward: { atk: 4, iq: 3 },
  },
  {
    id: 'm15',
    type: 'MATH',
    level: 4,
    subType: 'SEQUENCE',
    title: '🧠 Ngã tư: Dãy số nâng cao',
    question: 'Điền số tiếp theo: 1, 2, 4, 7, 11, ?',
    options: ['15', '16', '18'],
    answer: '16',
    reward: { atk: 4, iq: 3 },
  },

  // ===== LEVEL 5 (boss gate - khó hơn chút) =====
  {
    id: 'm16',
    type: 'MATH',
    level: 5,
    subType: 'LOGIC',
    title: '🧠 Boss Gate: Trí tuệ',
    question:
      'Có 3 hộp: hộp Táo, hộp Cam, hộp Táo & Cam. Tất cả đều dán sai nhãn. Mở 1 hộp, nên mở hộp nào để suy ra đúng nhãn các hộp còn lại?',
    options: ['Mở hộp Táo', 'Mở hộp Cam', 'Mở hộp Táo & Cam'],
    answer: 'Mở hộp Táo & Cam',
    reward: { atk: 6, iq: 5 },
  },
  {
    id: 'm17',
    type: 'MATH',
    level: 5,
    subType: 'LOGIC',
    title: '🧠 Boss Gate: Số học',
    question:
      'Một số có 2 chữ số. Tổng 2 chữ số bằng 9. Nếu đổi chỗ 2 chữ số thì số mới lớn hơn số cũ 27. Số đó là?',
    options: ['36', '45', '54'],
    answer: '36',
    reward: { atk: 6, iq: 5 },
  },
];

export const SOCIAL_QUESTIONS: QuizQuestion[] = [
  // ===== LEVEL 1 (cơ bản) =====
  {
    id: 's1',
    type: 'SOCIAL',
    level: 1,
    subType: 'EMOTION',
    title: '❤️ Bạn bè: Xin lỗi',
    question: 'Bạn lỡ nói lời làm bạn buồn, bạn nên…',
    options: ['Giả vờ không biết', 'Xin lỗi và sửa sai', 'Đổ lỗi cho bạn'],
    answer: 'Xin lỗi và sửa sai',
    reward: { empathy: 2, hp: 8 },
  },
  {
    id: 's2',
    type: 'SOCIAL',
    level: 1,
    subType: 'ETHICS',
    title: '❤️ Trường học: Xếp hàng',
    question: 'Khi xếp hàng ở căn-tin, bạn nên…',
    options: ['Chen lên', 'Đứng đúng thứ tự', 'Đẩy người khác'],
    answer: 'Đứng đúng thứ tự',
    reward: { empathy: 2, hp: 8 },
  },
  {
    id: 's3',
    type: 'SOCIAL',
    level: 1,
    subType: 'HELP',
    title: '❤️ Giúp đỡ',
    question: 'Thấy bạn bị ngã, bạn sẽ…',
    options: ['Cười', 'Bỏ đi', 'Đỡ bạn dậy và hỏi thăm'],
    answer: 'Đỡ bạn dậy và hỏi thăm',
    reward: { empathy: 2, hp: 8 },
  },

  // ===== LEVEL 2 (tình huống rõ hơn) =====
  {
    id: 's4',
    type: 'SOCIAL',
    level: 2,
    subType: 'SHARING',
    title: '❤️ Chia sẻ',
    question: 'Bạn có 1 món đồ chơi và 2 bạn muốn chơi cùng. Bạn nên…',
    options: ['Giữ hết', 'Chia lượt chơi', 'Bắt bạn khác đi chỗ khác'],
    answer: 'Chia lượt chơi',
    reward: { empathy: 3, hp: 10 },
  },
  {
    id: 's5',
    type: 'SOCIAL',
    level: 2,
    subType: 'EMOTION',
    title: '❤️ Cảm xúc',
    question: 'Khi tức giận, cách tốt nhất là…',
    options: ['Đập đồ', 'Hít thở sâu và bình tĩnh', 'La hét vào người khác'],
    answer: 'Hít thở sâu và bình tĩnh',
    reward: { empathy: 3, hp: 10 },
  },
  {
    id: 's6',
    type: 'SOCIAL',
    level: 2,
    subType: 'ETHICS',
    title: '❤️ Trung thực',
    question: 'Bạn nhặt được bút của người khác trong lớp. Bạn nên…',
    options: ['Giữ luôn', 'Hỏi xem ai bị mất và trả lại', 'Vứt đi'],
    answer: 'Hỏi xem ai bị mất và trả lại',
    reward: { empathy: 3, hp: 10 },
  },

  // ===== LEVEL 3 (nâng khó) =====
  {
    id: 's7',
    type: 'SOCIAL',
    level: 3,
    subType: 'SAFETY',
    title: '❤️ An toàn online',
    question: 'Người lạ nhắn tin xin địa chỉ nhà, bạn nên…',
    options: ['Gửi luôn', 'Không trả lời và báo người lớn', 'Trêu lại'],
    answer: 'Không trả lời và báo người lớn',
    reward: { empathy: 4, hp: 10 },
  },
  {
    id: 's8',
    type: 'SOCIAL',
    level: 3,
    subType: 'EMOTION',
    title: '❤️ Mâu thuẫn',
    question:
      'Bạn và bạn thân cãi nhau. Cách nào giúp hai bạn làm hòa tốt nhất?',
    options: [
      'Im lặng mãi',
      'Nói chuyện bình tĩnh và lắng nghe',
      'Kêu người khác nói xấu bạn ấy',
    ],
    answer: 'Nói chuyện bình tĩnh và lắng nghe',
    reward: { empathy: 4, hp: 12 },
  },
  {
    id: 's9',
    type: 'SOCIAL',
    level: 3,
    subType: 'HELP',
    title: '❤️ Can đảm',
    question: 'Thấy bạn bị bắt nạt, điều nào vừa an toàn vừa giúp được bạn?',
    options: [
      'Đánh nhau ngay',
      'Báo thầy cô/người lớn và đứng cạnh động viên bạn',
      'Quay video đăng mạng',
    ],
    answer: 'Báo thầy cô/người lớn và đứng cạnh động viên bạn',
    reward: { empathy: 4, hp: 12 },
  },

  // ===== LEVEL 4 (tinh tế hơn) =====
  {
    id: 's10',
    type: 'SOCIAL',
    level: 4,
    subType: 'ETHICS',
    title: '❤️ Công bằng',
    question:
      'Trong nhóm làm bài, một bạn không làm gì nhưng muốn ghi tên. Bạn nên…',
    options: [
      'Cho bạn ấy ghi tên để khỏi mất lòng',
      'Nói rõ việc cần chia đều và nhắc bạn cùng làm',
      'Tố bạn ấy trước cả lớp',
    ],
    answer: 'Nói rõ việc cần chia đều và nhắc bạn cùng làm',
    reward: { empathy: 5, hp: 14 },
  },
  {
    id: 's11',
    type: 'SOCIAL',
    level: 4,
    subType: 'SAFETY',
    title: '❤️ An toàn nơi công cộng',
    question: 'Đi siêu thị bị lạc bố mẹ, bạn nên làm gì trước?',
    options: [
      'Chạy lung tung tìm',
      'Đứng yên ở quầy thông tin/bảo vệ và nhờ giúp',
      'Đi theo người lạ dẫn đường',
    ],
    answer: 'Đứng yên ở quầy thông tin/bảo vệ và nhờ giúp',
    reward: { empathy: 5, hp: 14 },
  },

  // ===== LEVEL 5 (boss gate) =====
  {
    id: 's12',
    type: 'SOCIAL',
    level: 5,
    subType: 'ETHICS',
    title: '❤️ Boss Gate: Quyết định khó',
    question:
      'Nếu bạn thấy bạn mình gian lận trong bài kiểm tra, điều tốt nhất là…',
    options: [
      'Làm ngơ',
      'Nhắc bạn dừng lại hoặc báo người lớn',
      'Gian lận theo',
    ],
    answer: 'Nhắc bạn dừng lại hoặc báo người lớn',
    reward: { empathy: 6, hp: 18 },
  },
  {
    id: 's13',
    type: 'SOCIAL',
    level: 5,
    subType: 'EMOTION',
    title: '❤️ Boss Gate: Tự chủ',
    question:
      'Khi bị chọc tức liên tục, cách nào giúp bạn “mạnh mẽ” mà không làm ai bị tổn thương?',
    options: [
      'Chọc lại cho bằng',
      'Bình tĩnh, rời khỏi tình huống và nói với người lớn',
      'Đập đồ để xả',
    ],
    answer: 'Bình tĩnh, rời khỏi tình huống và nói với người lớn',
    reward: { empathy: 6, hp: 18 },
  },
];
